name: Auto-generate-and-push-pdf

on:
  pull_request:
    branches:
    - master
  push:
    branches: 
      - master

jobs:
  Generate-and-push-pdf:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup TeX
      run: |
        sudo apt-get install texlive-lang-japanese
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install texlive-lang-cjk
        sudo apt-get install texlive-fonts-recommended
        sudo apt-get install texlive-fonts-extra
        sudo apt-get install xdvik-ja
        sudo apt-get install gv
    - name: Generate pdf
      run: |
        /usr/bin/platex graduation-thesis.tex
        /usr/bin/platex graduation-thesis.tex
        /usr/bin/dvipdfmx graduation-thesis.dvi
    - name: Commit pdf file
      run: |
        if [ $(git status --porcelain | grep .pdf$ | wc -l) -ne 0 ] ; then
          git config --local user.email shoara0509@gmail.com
          git commit *.pdf -m "pdf updated by GitHub Actions"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
