name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches: 
      - master

jobs:
  Generate-and-push-pdf:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Setup TeX
      run: |
        brew cask install mactex-no-gui
        ls
        echo "1"
        sudo /Library/TeX/texbin/tlmgr update --self --all
        /Library/TeX/texbin/platex graduation-thesis.tex
        /Library/TeX/texbin.platex graduation-thesis.tex
        /Library/TeX/texbin.dvipdfmx graduation-thesis.tex
        echo "2"
        git commit *.pdf -m "pdf updated by GitHub Actions"
        git push -u master
        
