name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches: 
      - master

jobs:
  Generate-and-push-pdf:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup TeX
      run: |
        sudo apt-get install texlive-lang-japanese
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install texlive-lang-cjk
        sudo apt-get install texlive-fonts-recommended
        sudo apt-get install texlive-fonts-extra
        sudo apt-get install xdvik-ja
        sudo apt-get install gv
        tex_dir=`sudo dpkg -L {texlive-lang-japanese}`
        eval `echo "sudo $tex_dir/tlmgr path add"`
    - name: Generate pdf
      run: |
        kanji-config-updmap-sys ipaex
        uplatex graduation-thesis.tex
        uplatex graduation-thesis.tex
        dvipdfmx graduation-thesis.dvi
    - name: Push
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ $(git status --porcelain | grep .pdf$ | wc -l) -ne 0 ] ; then
            git remote set-url origin git@github.com:aosa4054/graduation-thesis.git
            git commit *.pdf -m "pdf updated by GitHub Actions"
            git push origin HEAD:master
          fi
