name: Auto-generate-and-push-pdf

on:
  pull_request:
    branches:
    - master
  push:
    branches: 
      - master

jobs:
  Generate-and-push-pdf:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup TeX
      run: |
        sudo apt-get install texlive-lang-japanese
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install texlive-lang-cjk
        sudo apt-get install texlive-fonts-recommended
        sudo apt-get install texlive-fonts-extra
        sudo apt-get install gv
    - name: Merge bib files
      run: |
        for bib in $(ls references | grep .bib$);do path="references/$bib";author=`cat $path | grep "^author =" | cut -f 2 -d "=" | sed -e "s/^ \"//" -e "s/\"\,$//" -e "s/\,//g" | cut -f 1 -d " "`;year=`cat $path| grep "^year =" | cut -c 9-12`;key=$author-$year;cat $path | sed -e "/^abstract/d" -e "s/^\(@.*\){.*\,/\1{$key,/"; done | awk '{print}{system("")}' > references.bib
    - name: Generate pdf
      run: |
        /usr/bin/platex graduation-thesis.tex
        /usr/bin/pbibtex graduation-thesis
        /usr/bin/platex graduation-thesis.tex
        /usr/bin/platex graduation-thesis.tex
        /usr/bin/dvipdfmx graduation-thesis.dvi
    - name: Push pdf file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://aosa4054:${GITHUB_TOKEN}@github.com/aosa4054/graduation-thesis.git
        git config user.email shoara0509@gmail.com
        git config user.name showtara
        if [ $(git status --porcelain | grep .bib$ | wc -l) -ne 0 ] ; then
          git commit *.bib -m "references updated by GitHub Actions"
          git push origin HEAD:master
        fi
        if [ $(git status --porcelain | grep .pdf$ | wc -l) -ne 0 ] ; then
          git commit *.pdf -m "pdf updated by GitHub Actions"
          git push origin HEAD:master
        fi
