name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches: 
      - master

jobs:
  Generate-and-push-pdf:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - uses: actions/cache@preview
      id: cache
      with:
        path: /Library/TeX/texbin
        key: ${{ runner.os }}-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/README.md')) }}
        restore-keys: |
          ${{ runner.os }}-cache-
    - name: Setup TeX
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        brew cask install mactex-no-gui
    - name: Update tlmgr
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo /Library/TeX/texbin/tlmgr update --self --all 
    - name: Generate pdf
      if: always()
      run: |
        /Library/TeX/texbin/platex graduation-thesis.tex
        /Library/TeX/texbin/platex graduation-thesis.tex
        /Library/TeX/texbin/dvipdfmx graduation-thesis.dvi
    - name: Push
      if: always()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ $(git status --porcelain | grep .pdf$ | wc -l) -ne 0 ] ; then
            git remote set-url origin git@github.com:aosa4054/graduation-thesis.git
            git commit *.pdf -m "pdf updated by GitHub Actions"
            git push origin HEAD:master
          fi
