name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches: 
      - master

jobs:
  Generate-and-push-pdf:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Setup TeX
      run: |
        brew cask install mactex-no-gui
        touch ~/.bash_profile
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
        export PATH="/Library/TeX/texbin:$PATH"
        echo "1"
        source ~/.bash_profile
        echo "2"
        sudo tlmgr update --self --all
        platex graduation-thesis.tex
        platex graduation-thesis.tex
        dvipdfmx graduation-thesis.tex
        echo "3"
        git commit *.pdf -m "pdf updated by GitHub Actions"
        git push -u master
      shell: bash
