name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches: 
      - master

jobs:
  Generate-and-push-pdf:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Reset branch
      run: |
        git reset --hard origin/$GITHUB_REF
    - name: Setup TeX
      run: |
        brew cask install mactex-no-gui
    - name: Update tlmgr
      run: |
        /Library/TeX/texbin/tlmgr update --self --all 
    - name: Generate pdf
      if: always()
      run: |
        /Library/TeX/texbin/platex graduation-thesis.tex
        /Library/TeX/texbin/platex graduation-thesis.tex
        /Library/TeX/texbin/dvipdfmx graduation-thesis.dvi
    - name: Push
      if: always()
      run: |
        if [ $(git status --porcelain | grep .pdf$ | wc -l) -ne 0 ] ; then
          git commit *.pdf -m "pdf updated by GitHub Actions"
          git push -u master
        fi
