name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches: 
      - master

jobs:
  Generate-and-push-pdf:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Setup TeX
      run: |
        brew cask install mactex-no-gui
        exec $SHELL -l
        sudo tlmgr update --self --all
    - name: Setpu Pandoc
      run: |
    - name: Typeset and generate pdf
      run: |
        platex graduation-thesis.tex
        platex graduation-thesis.tex
    - name: Push
      run: |
        echo $GITHUB_REF
        git commit *.pdf -m "pdf updated by GitHub Actions"
        git push -u master
